# -*- coding: utf-8 -*-
"""tiktok_frame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CI37_UNKuQDL0Rf8FinRaSoiH9MqEJuo
"""

import cv2
import os

print(cv2.__version__)

filepath = '/content/drive/MyDrive/tiktok/건전영상004.mp4'
video = cv2.VideoCapture(filepath)

if not video.isOpened():
    print("Could not open:", filepath)
    exit(0)

# 비디오 파일 정보 출력
length = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = video.get(cv2.CAP_PROP_FPS)

print("length:", length)
print("width:", width)
print("height:", height)
print("fps:", fps)

# 디렉토리 생성
directory = os.path.splitext(filepath)[0]  # 동영상 파일명에서 확장자를 제외한 부분을 디렉토리명으로 사용
try:
    if not os.path.exists(directory):
        os.makedirs(directory)
except OSError:
    print('Error: Creating directory -', directory)
    exit(0)

count = 0
while video.isOpened():
    ret, image = video.read()
    if not ret:
        break
    if int(video.get(1)) % int(fps) == 0:  # 1초마다 이미지 추출
        cv2.imwrite(directory + "/frame%d.jpg" % count, image)
        print('Saved frame number:', int(video.get(1)))
        count += 1

video.release()